package com.zntsns.awardtrace.award;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import org.hibernate.annotations.Formula;
import org.hibernate.annotations.Immutable;

/**
 * A read model; the pipeline projects this table from award transactions (ADR 0012). Associations are lazy, so load
 * an award through {@link AwardRepository}, which fetches them in the same query.
 */
@Entity
@Immutable
public class Award {

    @Id
    private String awardId;

    private String piid;
    private String parentPiid;
    private String awardType;
    private String description;
    // Keys the classifier's category for the description (doc 09).
    private String descriptionHash;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "awarding_toptier_code")
    private Agency awardingToptier;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "awarding_subtier_code")
    private Agency awardingSubtier;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "funding_toptier_code")
    private Agency fundingToptier;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "recipient_uei")
    private Recipient recipient;

    private String naicsCode;
    private String naicsDescription;
    private String pscCode;
    private String pscDescription;

    // Computed by PostgreSQL with the same function the indexer uses, so the two can't disagree.
    @Formula("psc_baseline_category(psc_code)")
    private String baselineCategory;
    private String popStateCode;
    private String popCountryCode;
    private BigDecimal totalObligated;
    private BigDecimal potentialTotalValue;
    private LocalDate popStartDate;
    private LocalDate popEndDate;
    private LocalDate firstActionDate;
    private LocalDate lastActionDate;

    // Generated by PostgreSQL from last_action_date.
    @Column(insertable = false, updatable = false)
    private Short fiscalYear;

    private Instant sourceModifiedAt;
    private long indexVersion;
    private int transactionCount;

    // Set when every transaction is deleted; such awards are kept only for the index to drop.
    private Instant deletedAt;

    protected Award() {
    }

    public String awardId() {
        return awardId;
    }

    public String piid() {
        return piid;
    }

    public String parentPiid() {
        return parentPiid;
    }

    public String awardType() {
        return awardType;
    }

    public String description() {
        return description;
    }

    public String descriptionHash() {
        return descriptionHash;
    }

    public Agency awardingToptier() {
        return awardingToptier;
    }

    public Agency awardingSubtier() {
        return awardingSubtier;
    }

    public Agency fundingToptier() {
        return fundingToptier;
    }

    public Recipient recipient() {
        return recipient;
    }

    public String naicsCode() {
        return naicsCode;
    }

    public String naicsDescription() {
        return naicsDescription;
    }

    public String pscCode() {
        return pscCode;
    }

    public String pscDescription() {
        return pscDescription;
    }

    /** The category the PSC implies (doc 09); null without a PSC. */
    public String baselineCategory() {
        return baselineCategory;
    }

    public String popStateCode() {
        return popStateCode;
    }

    public String popCountryCode() {
        return popCountryCode;
    }

    public BigDecimal totalObligated() {
        return totalObligated;
    }

    public BigDecimal potentialTotalValue() {
        return potentialTotalValue;
    }

    public LocalDate popStartDate() {
        return popStartDate;
    }

    public LocalDate popEndDate() {
        return popEndDate;
    }

    public LocalDate firstActionDate() {
        return firstActionDate;
    }

    public LocalDate lastActionDate() {
        return lastActionDate;
    }

    public int fiscalYear() {
        return fiscalYear;
    }

    public Instant sourceModifiedAt() {
        return sourceModifiedAt;
    }

    public long indexVersion() {
        return indexVersion;
    }

    public int transactionCount() {
        return transactionCount;
    }
}
